const Property = [
	{
		id: 1,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-1",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 2,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-2",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 3,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 4,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-4",
		isFor: "Sale",
		isPopular: true,
	},
	{
		id: 5,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-5",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 6,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5236,
		image: "property-6",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 7,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-7",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 8,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-8",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 9,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-9",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 10,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-10",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 11,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-1",
		isFor: "Sale",
		isPopular: true,
	},
	{
		id: 12,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-2",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 13,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 14,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 15,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-5",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 16,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-6",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 17,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-7",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 18,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5236,
		image: "property-8",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 19,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-9",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 20,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-10",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 21,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-1",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 22,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-2",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 23,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 24,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 25,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-1",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 26,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-2",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 27,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 28,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-4",
		isFor: "Sale",
		isPopular: true,
	},
	{
		id: 29,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-5",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 30,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5236,
		image: "property-6",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 31,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-7",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 32,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-8",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 33,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-9",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 34,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-10",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 35,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-1",
		isFor: "Sale",
		isPopular: true,
	},
	{
		id: 36,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-2",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 37,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 38,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 39,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-5",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 40,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-6",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 41,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-7",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 42,
		name: "RCE Theaters",
		location: {
			street: "8558 Pecan St.",
			address: "907 S Beckford Dr, Henderson, NC 27536",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5236,
		image: "property-8",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 43,
		name: "Costco Wholesale",
		location: {
			street: "8558 Parker Rd.",
			address: "1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-9",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 44,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-10",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 45,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-1",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 46,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-2",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 47,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 48,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 49,
		name: "Regal North Hills",
		location: {
			street: "3890 Poplar Dr.",
			address: "4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
];

export default Property