const Property = [
	{
		id: 1,
		location: {
			street: "8558 Pecan St.",
			address: "RCE Threaters - 907 S Beckford Dr, Henderson, NC 27536",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-1",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 2,
		location: {
			street: "8558 Parker Rd.",
			address: "Costco Wholesale - 1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-2",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 3,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 4,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-4",
		isFor: "Sale",
		isPopular: true,
	},
	{
		id: 5,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-5",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 6,
		location: {
			street: "8558 Pecan St.",
			address: "RCE Threaters - 907 S Beckford Dr, Henderson, NC 27536",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5236,
		image: "property-6",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 7,
		location: {
			street: "8558 Parker Rd.",
			address: "Costco Wholesale - 1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-7",
		isFor: "Sale",
		isPopular: false,
	},
	{
		id: 8,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-8",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 9,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-9",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 10,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-10",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 11,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-1",
		isFor: "Sale",
		isPopular: true,
	},
	{
		id: 12,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-2",
		isFor: "Rent",
		isPopular: false,
	},
	{
		id: 13,
		location: {
			street: "8558 Pecan St.",
			address: "RCE Threaters - 907 S Beckford Dr, Henderson, NC 27536",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 14,
		location: {
			street: "8558 Parker Rd.",
			address: "Costco Wholesale - 1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 15,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-5",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 16,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-6",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 17,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-7",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 18,
		location: {
			street: "8558 Pecan St.",
			address: "RCE Threaters - 907 S Beckford Dr, Henderson, NC 27536",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5236,
		image: "property-8",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 19,
		location: {
			street: "8558 Parker Rd.",
			address: "Costco Wholesale - 1021 Oak Forest Ln, Myrtle Beach, SC",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 7255,
		image: "property-9",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 20,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 5256,
		image: "property-10",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 21,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "New York",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-1",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 22,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "London",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-2",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 23,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Paris",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 6235,
		image: "property-3",
		isFor: "Rent",
		isPopular: true,
	},
	{
		id: 24,
		location: {
			street: "3890 Poplar Dr.",
			address: "Regal North Hills - 4150 Main at North Hills St, Releigh",
			city: "Mumbai",
		},
		rooms: 3,
		bed: 4,
		bathroom: 1,
		area: 732,
		rent: 4200,
		image: "property-4",
		isFor: "Rent",
		isPopular: true,
	},
];

export default Property